[tool.poetry]
name = "fast-api-model-serving"
version = "1.0"
description = "Fast API for serving ML Models"
authors = ["iobruno <bruno.oliveira@n26brasil.com>"]

[tool.poetry.dependencies]
python = "~3.8"
fastapi = "0.78.0"
httpx = "^0.23.0"
Pillow = "^9.1.1"
uvicorn = "0.17.6"
tensorflow-aarch64 = { version = "2.9.0", markers = "platform_system == 'Linux' and platform_machine == 'aarch64'" }
tensorflow-cpu     = { version = "2.9.0", markers = "platform_system == 'Linux' and platform_machine == 'x86_64'" }
tensorflow-macos = { version = "2.9.0", markers = "platform_system == 'Darwin'" }
tensorflow-metal = { version = "0.5.0", markers = "platform_system == 'Darwin'" }


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
