[project]
name = ""
version = "1.0"
description = "Fast API for serving ML Models"
license = {text = "CC-BY-SA-4.0"}
readme = "README.md"
authors = [
    {name = "Bruno Oliveira", email = "bruno.ariev@gmail.com"},
]

requires-python = ">=3.10,<3.12"

dependencies = [
    "fastapi>=0.104.1",
    "httpx>=0.25.1",
    "Pillow>=10.1.0",
    "uvicorn>=0.24.0.post1",
    "tensorflow-metal>=1.1.0;    sys_platform == 'darwin'",
    "tensorflow-macos>=2.15.0;   sys_platform == 'darwin'",
    "tensorflow-cpu>=2.15.0;     sys_platform == 'linux' and platform_machine == 'x86_64'",
    "tensorflow-aarch64>=2.15.0; sys_platform == 'linux' and platform_machine == 'aarch64'",
]

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.1.6",
]
