[tool.poetry]
name = "fast-api-model-serving"
version = "0.1.0"
description = "Fast API for serving ML Models"
authors = ["iobruno <bruno.oliveira@n26brasil.com>"]

[tool.poetry.dependencies]
python = "~3.10"
fastapi = "0.78.0"
uvicorn = "0.17.6"
httpx = "^0.23.0"
tensorflow = "^2.9.1"
Pillow = "^9.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
